introspection:
  removeTrailingPeriodFromDescriptions: false
  schemaFile: ./schema.graphql
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2
  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true

info:
  title: EXIP GraphQL API Reference
  description: Export Insurance Policies

servers:
  - url: https://
    headers:
      - name: x-api-key
        example: ExampleKey
